server:
  port: 8534

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nikhilgrg7/Banking-Application
          clone-on-start: true