server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: CUSTOMER-SERVICE
  config:
    import: optional:configserver:http://localhost:8888


